#!/usr/bin/python

# Copyright 2017 Edmundo Carmona Antoranz
# Released under the terms of GPLv3

import sys


def read_stream(stream):
    line = ""
    while True:
        prevLine = line
        line = stream.readline()

        if len(line) == 0:
            # reached EOL
            break

        line = line.rstrip('\n')

        # we delete as many chars as prevLine
        for i in range(0, len(prevLine) - len(line)):
            sys.stdout.write('\b \b')
        # now we go back to the beginning of the line
        sys.stdout.write('\r')

        sys.stdout.write(line)


read_stream(sys.stdin)
sys.stdout.write('\n')
