#!/usr/bin/python

# Copyright 2017 Edmundo Carmona Antoranz
# Released under the terms of GPLv3

import sys


def read_stream(stream):
    line = ""
    while True:
        prevLine = line
        line = stream.readline()

        if len(line) == 0:
            # reached EOL
            break

        line = line.rstrip('\n')

        # we delete as many chars as prevLine
        for i in range(0, len(prevLine) - len(line)):
            sys.stdout.write('\b \b')
        # now we go back to the beginning of the line
        sys.stdout.write('\r')

        sys.stdout.write(line)

if len(sys.argv) == 1:
    # reading from stdin straight
    read_stream(sys.stdin)
else:
    # parameters were passed
    for i in range(1, len(sys.argv)):
        filename = sys.argv[i]
        if (filename == '-'):
            # reading from stdin
            read_stream(sys.stdin)
        else:
            # we need to make sure file exists
            try:
                infile = open(sys.argv[i], 'r')
                read_stream(infile)
                infile.close()
            except IOError as ioErr:
                print(ioErr)
sys.stdout.write('\n')
